name: JasonEarly
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7cb8b9'
    - '#992901'
    - '#fe6102'
    - '#faf4e6'
    - '#fac304'
  brandStrength: 1
  lightness: 0.14408258837647736
  saturation: 0.5
  rhythmicContrast: 0.7039087449666113
purpose: []
