name: JasonEarly
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6416
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#969696'
    - '#626262'
    - '#282828'
    - '#d1d1d1'
  brandStrength: 0.9027845170348883
  lightness: 0.14408258837647736
  saturation: 0.893340241862461
  rhythmicContrast: 0.7039087449666113
purpose: []
